### ISSUE TITLE
Maven dependency not working

### ISSUE THREAD

**Issue by StephaneBg** [whilu/LMBluetoothSdk#1]
Library cannot be found on Maven Central.

**Comment by whilu** [comment]
@StephaneBg Sorry, there are some errors when sync to `Maven Central`, you can use it with `Gradle` now, I will fix this problem as soon as possible. Thanks!

**Comment by whilu** [comment]
@StephaneBg the latest version `1.0.1` has been synchronized to Maven, I hope this library can help you. Thank you!
