### ISSUE TITLE
BLE scan

### ISSUE THREAD

**Issue by daimonkor** [whilu/LMBluetoothSdk#2]
Please add callback on finish/stop scanning BLE devices, 
Please add check if scanning now.
Thanks for your support.

**Comment by whilu** [comment]
@daimonkor OK, no problem, I will add this features as soon as possible. Thank you!

**Comment by whilu** [comment]
@daimonkor Hello, the latest version `1.0.1` supports obtaining the BLE scanning status, use callback `onActionDiscoveryStateChanged(String discoveryState)` like classic bluetooth to get scanning status. I hope this can help you!

**Comment by daimonkor** [comment]
Callback on scan work well.

**Comment by daimonkor** [comment]
Please add callback when characteristics are avialable, for example, characteristic available. Thanks for your support.

![Image of GATT server callback](http://i.prntscr.com/dc6f9762fa6c409e80177062336e023d.png)

**Comment by whilu** [comment]
Hi, i am a bit busy lately. i will add this features as soon as possible.
or you can make this code and PR, i will review the code and merge. Thanks!

Dima notifications@github.com于2016年2月3日 周三07:34写道：

**Comment by daimonkor** [comment]
I think I found your decision    mBluetoothListener.onActionDiscoveryStateChanged(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);
