### ISSUE TITLE
Missing permissions request for Android 6.0

### ISSUE THREAD

**Issue by pvxe** [whilu/LMBluetoothSdk#6]
[http://developer.android.com/intl/es/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id](url)
- Missing explicit permission request for ACCESS_FINE_LOCATION

Solution: 
[http://stackoverflow.com/questions/33142034/android-6-bluetooth](url)

**Comment by pvxe** [comment]
I know I could fork your repo and pull request the fix but now I don't have the time for it so that's why I opened the issue.

**Comment by whilu** [comment]
Thanks! I will fix this.

**Comment by whilu** [comment]
I think developers should add this runtime permission by themselves,  this will be better!
